include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/archive_workout_system/**
    - lib/archive_chad_workout/**
    - lib/archive_pending_fix/**
    - lib/screens/archive_quick_analysis/**
    - lib/screens/test/**
    - lib/screens/demo/**
    - lib/screens/tasks/**
    - lib/screens/ai/**
    - lib/screens/home/widgets/**
    - lib/screens/dream_journal/**
    - lib/screens/evolution/**
    - lib/widgets/dream_journal/**
    - lib/widgets/ai/**
    - lib/widgets/gamification/**
    - lib/widgets/progress/**
    - lib/widgets/settings/**
    - lib/widgets/statistics/**
    - lib/services/ai/**
    - lib/services/progress/**
    - lib/utils/**
    - lib/models/backup/**
    - test/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
