name: mission100
description: "Mission: 100 - 기가차드 밈 기반 개인화된 푸쉬업 마스터 앱, 6주 만에 100개 달성!"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.1.0+9

environment:
  sdk: ^3.5.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  google_sign_in: ^6.3.0

  # 결제 시스템
  in_app_purchase: ^3.1.13

  # 상태관리
  flutter_riverpod: ^3.0.0
  riverpod: ^3.0.0
  provider: ^6.1.2
  
  # 로컬 데이터베이스
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # 로컬 저장소
  shared_preferences: ^2.2.2
  
  # 알림
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1
  
  # 캘린더
  table_calendar: ^3.1.2
  
  # 차트 및 시각화
  fl_chart: ^0.66.2
  
  # 날짜 처리 및 국제화
  intl: 0.20.2
  
  # URL 런처 (유튜브 링크 열기용)
  url_launcher: ^6.3.1
  
  # 앱 정보
  package_info_plus: ^9.0.0

  # 디바이스 정보
  device_info_plus: ^12.1.0

  # 파일 관리
  file_picker: ^10.3.3
  path_provider: ^2.1.4
  permission_handler: ^12.0.1
  
  # 암호화 및 해시
  crypto: ^3.0.3
  encrypt: ^5.0.3

  # HTTP 요청
  http: ^1.2.2

  # 네트워크 연결 상태 감지
  connectivity_plus: ^6.0.5
  
  # 유튜브 플레이어
  youtube_player_flutter: ^9.1.1
  
  # Google Mobile Ads
  google_mobile_ads: ^6.0.0

  # 애니메이션
  confetti: ^0.8.0
  # lottie: ^2.7.0
  
  # UI 아이콘
  cupertino_icons: ^1.0.8
  
  # 소셜 공유
  share_plus: ^12.0.0

  # 비디오 재생
  video_player: ^2.10.0

  # 마크다운 지원 (법적 문서)
  flutter_markdown: ^0.6.18

dependency_overrides:
  # webview_flutter 호환성 문제 해결을 위한 버전 고정
  webview_flutter: 4.8.0
  webview_flutter_android: 3.16.7
  webview_flutter_wkwebview: 3.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 테스트용 패키지
  sqflite_common_ffi: ^2.3.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

  # 앱 아이콘 생성
  flutter_launcher_icons: ^0.14.4

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

  # 기가차드 이미지 assets
  assets:
    - assets/images/
    - assets/images/기본차드.jpg
    # 푸시업 자세 가이드 이미지 assets
    - assets/images/pushup_forms/
    - assets/images/pushup_forms/standard/
    - assets/images/pushup_forms/knee/
    - assets/images/pushup_forms/incline/
    - assets/images/pushup_forms/wide/
    - assets/images/pushup_forms/diamond/
    - assets/images/pushup_forms/decline/
    - assets/images/pushup_forms/archer/
    - assets/images/pushup_forms/pike/
    - assets/images/pushup_forms/clap/
    - assets/data/pushup_form_guide.json
    - assets/data/pushup_form_guide_en.json
    - assets/config/
    # 법적 문서
    - assets/legal/
  
  # 커스텀 폰트 (추후 추가 시)
  # fonts:
  #   - family: ChadFont
  #     fonts:
  #       - asset: fonts/ChadFont-Regular.ttf
  #       - asset: fonts/ChadFont-Bold.ttf
  #         weight: 700

# 앱 아이콘 설정
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/misson100_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/misson100_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/misson100_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/misson100_icon.png"
