/// Auto-generated character evolution data for DreamFlow (Lucid Dream App)
/// DO NOT EDIT - Generated by Mission App Factory v3.0
library;

class CharacterStage {
  final String id;
  final String name;
  final String nameShort;
  final String description;
  final int unlockDays;
  final String unlockMessage;
  final String imageFilename;
  final String color;
  final List<String> traits;

  const CharacterStage({
    required this.id,
    required this.name,
    required this.nameShort,
    required this.description,
    required this.unlockDays,
    required this.unlockMessage,
    required this.imageFilename,
    required this.color,
    required this.traits,
  });
}

class CharacterEvolution {
  static const String characterName = 'Lumi';
  static const String nameShort = 'LUMI';
  static const String concept = '자각몽 여정과 함께 성장하는 꿈의 요정';
  static const String personality = '신비롭고, 다정하고, 몽환적이며, 격려해주는';

  /// All evolution stages (6 stages)
  ///
  /// Premium policy:
  /// - Week 0-1 (Stage 1-2): FREE (permanently free)
  /// - Week 2+ (Stage 3-6): PREMIUM (access restricted)
  /// - First 14 days: Week 2+ access unlocked (level up requires XP)
  static List<CharacterStage> get stages => [
    const CharacterStage(
      id: 'stage1',
      name: '꿈 씨앗',
      nameShort: 'Seed',
      description: '자각몽 여정의 시작이에요. 작은 꿈의 씨앗이 싹트기 시작했어요!',
      unlockDays: 0,
      unlockMessage: '꿈의 세계로 첫 발을 내딛었어요! Lumi와 함께 자각몽을 배워볼까요?',
      imageFilename: 'stage0_sleepy_lumi.png',
      color: '#94A3B8',
      traits: ['호기심', '배움 시작', '꿈 기록'],
    ),
    const CharacterStage(
      id: 'stage2',
      name: '꿈나래',
      nameShort: 'Sprout',
      description: '꿈 일기 습관이 생겼어요. 매일 꿈을 기록하며 꿈의 패턴을 알아가고 있어요.',
      unlockDays: 7,
      unlockMessage: '꿈 일기 습관이 자리잡았어요! 이제 꿈을 더 선명하게 기억할 수 있어요.',
      imageFilename: 'stage1_aware_lumi.png',
      color: '#7DD3FC',
      traits: ['꿈 기억력', '패턴 인식', '일관성'],
    ),
    const CharacterStage(
      id: 'stage3',
      name: '루시드 새싹',
      nameShort: 'Lucid',
      description: '현실 점검(Reality Check)이 습관이 되었어요. 꿈 속에서 "이게 꿈인가?" 하고 물어볼 수 있어요.',
      unlockDays: 14,
      unlockMessage: 'Reality Check 마스터! 이제 꿈 속에서도 자각할 준비가 되었어요.',
      imageFilename: 'stage2_lucid_lumi.png',
      color: '#A78BFA',
      traits: ['현실 점검', 'MILD 기법', '자각 시작'],
    ),
    const CharacterStage(
      id: 'stage4',
      name: '몽상가',
      nameShort: 'Dreamer',
      description: '자각몽을 경험하기 시작했어요! 꿈 속에서 "이건 꿈이야!"라고 깨달을 수 있어요.',
      unlockDays: 28,
      unlockMessage: '첫 자각몽 경험! 꿈 속에서 자유를 느끼기 시작했네요.',
      imageFilename: 'stage3_dream_walker.png',
      color: '#34D399',
      traits: ['자각몽 경험', 'WBTB 기법', '꿈 안정화'],
    ),
    const CharacterStage(
      id: 'stage5',
      name: '드림 가이드',
      nameShort: 'Guide',
      description: '자각몽을 자주 경험하고, 꿈 속에서 원하는 것을 할 수 있어요. 꿈을 조절하는 법을 배웠어요.',
      unlockDays: 56,
      unlockMessage: '꿈의 세계를 탐험하는 가이드가 되었어요! 이제 꿈을 디자인할 수 있어요.',
      imageFilename: 'stage4_astral_traveler.png',
      color: '#F472B6',
      traits: ['꿈 조절', '비행 능력', '꿈 디자인'],
    ),
    const CharacterStage(
      id: 'stage6',
      name: '드림 스피릿',
      nameShort: 'Spirit',
      description: '자각몽의 달인이 되었어요. 원할 때 자각몽을 꾸고, 꿈 속에서 무엇이든 할 수 있어요.',
      unlockDays: 84,
      unlockMessage: '마스터 단계에 도달했어요! 당신은 진정한 드림 스피릿이에요.',
      imageFilename: 'stage5_oracle_lumi.png',
      color: '#8B5CF6',
      traits: ['완전한 자각', '꿈 마스터', '무한한 가능성'],
    ),
  ];

  /// Get stage for specific training days (DEPRECATED - use getStageForWeek)
  @Deprecated('Use getStageForWeek instead')
  static CharacterStage getStageForDays(int days) {
    return stages.lastWhere(
      (stage) => days >= stage.unlockDays,
      orElse: () => stages.first,
    );
  }

  /// Get stage for specific week level (XP-based)
  ///
  /// Week 0 = Stage 1 (Beginner - Dream Seed)
  /// Week 1 = Stage 2 (Developing - Dream Sprout)
  /// Week 2-3 = Stage 3 (Intermediate - Lucid Sprout)
  /// Week 4-6 = Stage 4 (Advanced - Dreamer)
  /// Week 7-13 = Stage 5 (Expert - Dream Guide)
  /// Week 14+ = Stage 6 (Master - Dream Spirit)
  static CharacterStage getStageForWeek(int weekLevel) {
    if (weekLevel <= 0) return stages[0];
    if (weekLevel == 1) return stages[1];
    if (weekLevel <= 3) return stages[2];
    if (weekLevel <= 6) return stages[3];
    if (weekLevel <= 13) return stages[4];
    return stages[5];
  }

  /// Get current stage index (0-based)
  static int getStageIndex(CharacterStage stage) {
    return stages.indexOf(stage);
  }

  /// Get next stage (null if already at max)
  static CharacterStage? getNextStage(CharacterStage current) {
    final index = getStageIndex(current);
    if (index >= stages.length - 1) return null;
    return stages[index + 1];
  }

  /// Get week level required for next stage
  static int? getWeekForNextStage(int currentWeek) {
    if (currentWeek >= 14) return null;

    // Week progression thresholds
    const thresholds = [0, 1, 2, 4, 7, 14];
    for (int threshold in thresholds) {
      if (currentWeek < threshold) return threshold;
    }
    return null;
  }

  /// Check if user can access specific week content
  static bool canAccessWeek(int weekLevel, int targetWeek, {bool isPremium = false}) {
    // Week 0-1 always accessible (free tier)
    if (targetWeek <= 1) return true;
    // Premium users can access all weeks
    if (isPremium) return true;
    // Check if user level is sufficient
    return weekLevel >= targetWeek;
  }

  /// Get next stage for week (alias for backwards compatibility)
  static CharacterStage? getNextStageForWeek(int weekLevel) {
    final currentStage = getStageForWeek(weekLevel);
    return getNextStage(currentStage);
  }
}
