/// Auto-generated character evolution data
/// DO NOT EDIT - Generated by Mission App Factory v2.1
library;

class CharacterStage {
  final String id;
  final String name;
  final String nameShort;
  final String description;
  final int unlockWeek;
  final String unlockMessage;
  final String imageFilename;
  final String color;
  final List<String> traits;

  const CharacterStage({
    required this.id,
    required this.name,
    required this.nameShort,
    required this.description,
    required this.unlockWeek,
    required this.unlockMessage,
    required this.imageFilename,
    required this.color,
    required this.traits,
  });
}

class CharacterEvolution {
  static const String characterName = 'Dream Spirit';
  static const String nameShort = 'Spirit';
  static const String concept = 'A mystical spirit guide that evolves as you master lucid dreaming';
  static const String personality = 'Wise, mystical, encouraging, dream-like';

  /// All evolution stages
  static List<CharacterStage> get stages => [
    const CharacterStage(
      id: 'stage0',
      name: 'Sleepy Ghost',
      nameShort: 'Sleepy',
      description: 'Just awakening to the dream realm. Barely conscious.',
      unlockWeek: 0,
      unlockMessage: 'Welcome to the Dream Realm! Your spirit guide awakens. 👻',
      imageFilename: 'stage0_sleepy_ghost.png',
      color: '#94A3B8',
      traits: ['unconscious', 'beginner', 'foggy'],
    ),
    const CharacterStage(
      id: 'stage1',
      name: 'Aware Wisp',
      nameShort: 'Aware',
      description: 'Beginning to perceive the dream world.',
      unlockWeek: 2,
      unlockMessage: 'Awareness grows! Your spirit is becoming conscious. ✨',
      imageFilename: 'stage1_aware_wisp.png',
      color: '#7DD3FC',
      traits: ['awakening', 'curious', 'learning'],
    ),
    const CharacterStage(
      id: 'stage2',
      name: 'Lucid Sprite',
      nameShort: 'Lucid',
      description: 'Can recognize dreams but control is limited.',
      unlockWeek: 4,
      unlockMessage: 'First lucid moments! Reality checks are working! 🌟',
      imageFilename: 'stage2_lucid_sprite.png',
      color: '#A78BFA',
      traits: ['aware', 'developing', 'excited'],
    ),
    const CharacterStage(
      id: 'stage3',
      name: 'Dream Walker',
      nameShort: 'Walker',
      description: 'Walking freely between dream and wake.',
      unlockWeek: 6,
      unlockMessage: 'Halfway there! You are now a Dream Walker! 🚶‍♂️✨',
      imageFilename: 'stage3_dream_walker.png',
      color: '#34D399',
      traits: ['confident', 'stable', 'balanced'],
    ),
    const CharacterStage(
      id: 'stage4',
      name: 'Astral Traveler',
      nameShort: 'Traveler',
      description: 'Exploring vast dream landscapes with ease.',
      unlockWeek: 8,
      unlockMessage: '8 weeks! Astral travel unlocked! 🌌',
      imageFilename: 'stage4_astral_traveler.png',
      color: '#F472B6',
      traits: ['explorer', 'adventurous', 'powerful'],
    ),
    const CharacterStage(
      id: 'stage5',
      name: 'Oneiroi Oracle',
      nameShort: 'Oracle',
      description: 'Wisdom of the dream realm flows through you.',
      unlockWeek: 10,
      unlockMessage: '10 weeks! Oracle wisdom achieved! 🔮',
      imageFilename: 'stage5_oneiroi_oracle.png',
      color: '#FCD34D',
      traits: ['wise', 'prophetic', 'enlightened'],
    ),
    const CharacterStage(
      id: 'stage6',
      name: 'Master of Dreams',
      nameShort: 'Master',
      description: 'Complete control over the dream realm. A true oneironaut.',
      unlockWeek: 14,
      unlockMessage: 'LEGENDARY! Dream Master achieved! You control reality! 👑🌙',
      imageFilename: 'stage6_dream_master.png',
      color: '#8B5CF6',
      traits: ['legendary', 'master', 'omnipotent'],
    ),
  ];

  /// Get stage for specific week
  static CharacterStage getStageForWeek(int week) {
    return stages.lastWhere(
      (stage) => week >= stage.unlockWeek,
      orElse: () => stages.first,
    );
  }

  /// Get next stage
  static CharacterStage? getNextStage(int currentWeek) {
    final currentIndex = stages.indexWhere((s) => currentWeek >= s.unlockWeek);
    if (currentIndex < stages.length - 1) {
      return stages[currentIndex + 1];
    }
    return null;
  }
}
