/// Auto-generated checklist data
/// DO NOT EDIT - Generated by Mission App Factory v2.1
library;

class ChecklistItem {
  final String id;
  final String name;
  final String nameKo;
  final String description;
  final String icon;
  final String? defaultTime;
  final int? priority;
  final int? countRequired;
  final int? intervalMinutes;
  final bool optional;
  final String? researchNote;

  const ChecklistItem({
    required this.id,
    required this.name,
    required this.nameKo,
    required this.description,
    required this.icon,
    this.defaultTime,
    this.priority,
    this.countRequired,
    this.intervalMinutes,
    this.optional = false,
    this.researchNote,
  });
}

class ChecklistData {
  /// Daily checklist items
  static List<ChecklistItem> get dailyChecklist => [
    ChecklistItem(
      id: 'dream_journal',
      name: 'Dream Journal (PRIORITY #1)',
      nameKo: '꿈 일기 작성 (최우선)',
      description: 'Write down dreams immediately after waking. Research shows dream recall is the #1 predictor of lucid dream success.',
      icon: '📔',
      defaultTime: '07:00',
      priority: 1,
      researchNote: 'Superior dream recall = higher success rate',
    ),
    ChecklistItem(
      id: 'reality_check_2hr',
      name: 'Reality Checks (5x, every 2hrs)',
      nameKo: '현실 확인 (5회, 2시간마다)',
      description: 'Check reality every 2 hours while awake. Research: 5 times daily, combined with WBTB+MILD is effective.',
      icon: '👁️',
      countRequired: 5,
      intervalMinutes: 120,
      researchNote: 'Reality checks alone are NOT effective. Must combine with WBTB+MILD',
    ),
    ChecklistItem(
      id: 'wbtb_alarm',
      name: 'WBTB Alarm (Wake Back to Bed)',
      nameKo: 'WBTB 알람 (5시간 후)',
      description: 'Set alarm for 5 hours after sleep. Wake briefly, practice MILD, then sleep again. Research: 46% success rate!',
      icon: '⏰',
      defaultTime: '23:00',
      priority: 2,
      researchNote: 'WBTB + MILD = highest success rate (46%)',
    ),
    ChecklistItem(
      id: 'mild_wbtb',
      name: 'MILD Technique (during WBTB)',
      nameKo: 'MILD 기법 (WBTB 중)',
      description: 'After 5hr alarm: Stay awake 5-10min. Repeat "Next time I am dreaming, I will remember I am dreaming". Fall asleep within 10min.',
      icon: '🧠',
      defaultTime: '04:00',
      priority: 2,
      researchNote: 'Fall asleep within 10min after MILD = success predictor',
    ),
    ChecklistItem(
      id: 'bedtime_preparation',
      name: 'Bedtime Dream Prep',
      nameKo: '취침 전 준비',
      description: 'Review dream journal, set intention for lucidity. Keep journal by bed.',
      icon: '🌙',
      defaultTime: '22:30',
    ),
    ChecklistItem(
      id: 'ssild_technique',
      name: 'SSILD Technique (Advanced, Optional)',
      nameKo: 'SSILD 기법 (고급, 선택)',
      description: 'Senses Initiated Lucid Dream: Cycle through sight, sound, body sensations. As effective as MILD.',
      icon: '🧘',
      optional: true,
      researchNote: 'SSILD is similarly effective to MILD',
    ),
  ];

  /// Get priority 1 items
  static List<ChecklistItem> get priority1Items =>
      dailyChecklist.where((item) => item.priority == 1).toList();

  /// Get priority 2 items
  static List<ChecklistItem> get priority2Items =>
      dailyChecklist.where((item) => item.priority == 2).toList();

  /// Get regular items (no priority)
  static List<ChecklistItem> get regularItems =>
      dailyChecklist.where((item) => item.priority == null && !item.optional).toList();

  /// Get optional items
  static List<ChecklistItem> get optionalItems =>
      dailyChecklist.where((item) => item.optional).toList();
}
